export interface GeneralQuestion {
  q: string;
  o: string[];
  a: number;
}

export const GENERAL_QUESTIONS: Record<string, GeneralQuestion[]> = {
  world: [
    { q: "Capital of USA?", o: ["New York", "Washington DC", "Los Angeles", "Chicago"], a: 1 },
    { q: "Capital of UK?", o: ["London", "Paris", "Berlin", "Rome"], a: 0 },
    { q: "Capital of France?", o: ["Madrid", "Rome", "Paris", "Berlin"], a: 2 },
    { q: "Capital of Germany?", o: ["Munich", "Berlin", "Frankfurt", "Hamburg"], a: 1 },
    { q: "Capital of Italy?", o: ["Venice", "Rome", "Milan", "Naples"], a: 1 },
    { q: "Capital of Japan?", o: ["Tokyo", "Seoul", "Beijing", "Bangkok"], a: 0 },
    { q: "Capital of China?", o: ["Shanghai", "Beijing", "Hong Kong", "Wuhan"], a: 1 },
    { q: "Capital of Russia?", o: ["Moscow", "Kyiv", "Minsk", "Warsaw"], a: 0 },
    { q: "Capital of Canada?", o: ["Toronto", "Ottawa", "Vancouver", "Montreal"], a: 1 },
    { q: "Capital of Australia?", o: ["Sydney", "Melbourne", "Canberra", "Perth"], a: 2 },
    { q: "Capital of India?", o: ["Delhi", "Mumbai", "Kolkata", "Chennai"], a: 0 },
    { q: "Capital of Brazil?", o: ["Rio", "Sao Paulo", "Brasilia", "Salvador"], a: 2 },
    { q: "Capital of Argentina?", o: ["Buenos Aires", "Lima", "Santiago", "Bogota"], a: 0 },
    { q: "Capital of Mexico?", o: ["Mexico City", "Cancun", "Monterrey", "Tijuana"], a: 0 },
    { q: "Capital of South Africa?", o: ["Cape Town", "Pretoria", "Johannesburg", "Durban"], a: 1 },
    { q: "Capital of Egypt?", o: ["Cairo", "Alexandria", "Giza", "Luxor"], a: 0 },
    { q: "Capital of Turkey?", o: ["Istanbul", "Ankara", "Izmir", "Antalya"], a: 1 },
    { q: "Capital of Saudi Arabia?", o: ["Riyadh", "Jeddah", "Mecca", "Medina"], a: 0 },
    { q: "Capital of UAE?", o: ["Dubai", "Abu Dhabi", "Sharjah", "Ajman"], a: 1 },
    { q: "Capital of Pakistan?", o: ["Karachi", "Islamabad", "Lahore", "Peshawar"], a: 1 },
    { q: "Capital of Bangladesh?", o: ["Dhaka", "Chittagong", "Khulna", "Sylhet"], a: 0 },
    { q: "Capital of Nepal?", o: ["Kathmandu", "Pokhara", "Lalitpur", "Biratnagar"], a: 0 },
    { q: "Capital of Sri Lanka?", o: ["Colombo", "Kandy", "Galle", "Jaffna"], a: 0 },
    { q: "Capital of Afghanistan?", o: ["Kabul", "Herat", "Kandahar", "Mazar"], a: 0 },
    { q: "Capital of Iran?", o: ["Tehran", "Isfahan", "Shiraz", "Tabriz"], a: 0 },
    { q: "Capital of Iraq?", o: ["Baghdad", "Basra", "Mosul", "Karbala"], a: 0 },
    { q: "Capital of Thailand?", o: ["Bangkok", "Phuket", "Chiang Mai", "Pattaya"], a: 0 },
    { q: "Capital of Indonesia?", o: ["Jakarta", "Bali", "Surabaya", "Bandung"], a: 0 },
    { q: "Capital of Philippines?", o: ["Manila", "Cebu", "Davao", "Quezon"], a: 0 },
    { q: "Capital of Vietnam?", o: ["Hanoi", "Ho Chi Minh", "Da Nang", "Hue"], a: 0 },
    { q: "Capital of South Korea?", o: ["Seoul", "Busan", "Incheon", "Daegu"], a: 0 },
    { q: "Capital of North Korea?", o: ["Pyongyang", "Seoul", "Busan", "Incheon"], a: 0 },
    { q: "Capital of Spain?", o: ["Barcelona", "Madrid", "Valencia", "Seville"], a: 1 },
    { q: "Capital of Portugal?", o: ["Lisbon", "Porto", "Braga", "Coimbra"], a: 0 },
    { q: "Capital of Netherlands?", o: ["Amsterdam", "Rotterdam", "Utrecht", "Hague"], a: 0 },
    { q: "Capital of Belgium?", o: ["Brussels", "Antwerp", "Ghent", "Bruges"], a: 0 },
    { q: "Capital of Switzerland?", o: ["Zurich", "Geneva", "Bern", "Basel"], a: 2 },
    { q: "Capital of Sweden?", o: ["Stockholm", "Oslo", "Copenhagen", "Helsinki"], a: 0 },
    { q: "Capital of Norway?", o: ["Oslo", "Bergen", "Trondheim", "Stavanger"], a: 0 },
    { q: "Capital of Denmark?", o: ["Copenhagen", "Aarhus", "Odense", "Aalborg"], a: 0 },
    { q: "Capital of Finland?", o: ["Helsinki", "Turku", "Tampere", "Oulu"], a: 0 },
    { q: "Capital of Poland?", o: ["Warsaw", "Krakow", "Gdansk", "Wroclaw"], a: 0 },
    { q: "Capital of Ukraine?", o: ["Kyiv", "Lviv", "Odessa", "Kharkiv"], a: 0 },
    { q: "Capital of Greece?", o: ["Athens", "Thessaloniki", "Sparta", "Patras"], a: 0 },
    { q: "Capital of Austria?", o: ["Vienna", "Salzburg", "Graz", "Linz"], a: 0 },
    { q: "Capital of Hungary?", o: ["Budapest", "Debrecen", "Szeged", "Pecs"], a: 0 },
    { q: "Capital of Czech Republic?", o: ["Prague", "Brno", "Ostrava", "Plzen"], a: 0 },
    { q: "Capital of Romania?", o: ["Bucharest", "Cluj", "Timisoara", "Iasi"], a: 0 },
    { q: "Capital of Bulgaria?", o: ["Sofia", "Plovdiv", "Varna", "Burgas"], a: 0 },
    { q: "Capital of New Zealand?", o: ["Auckland", "Wellington", "Christchurch", "Hamilton"], a: 1 },
    { q: "Largest country in the world?", o: ["USA", "China", "Russia", "Canada"], a: 2 },
    { q: "Smallest country?", o: ["Monaco", "Vatican City", "Malta", "Luxembourg"], a: 1 },
    { q: "Most populous country?", o: ["India", "USA", "China", "Brazil"], a: 0 },
    { q: "Which country has most islands?", o: ["Indonesia", "Philippines", "Sweden", "Japan"], a: 2 },
    { q: "Which country has no capital?", o: ["Nauru", "Monaco", "Vatican", "Malta"], a: 0 },
    { q: "Currency of USA?", o: ["Dollar", "Euro", "Pound", "Yen"], a: 0 },
    { q: "Currency of UK?", o: ["Euro", "Pound", "Dollar", "Franc"], a: 1 },
    { q: "Currency of Japan?", o: ["Yuan", "Won", "Yen", "Dollar"], a: 2 },
    { q: "Currency of China?", o: ["Yen", "Yuan", "Won", "Dollar"], a: 1 },
    { q: "Currency of India?", o: ["Rupee", "Dollar", "Taka", "Rial"], a: 0 },
    { q: "Which country is known as Land of Rising Sun?", o: ["China", "Japan", "Korea", "Thailand"], a: 1 },
    { q: "Land of Kangaroos?", o: ["New Zealand", "Australia", "USA", "Canada"], a: 1 },
    { q: "Land of Pharaohs?", o: ["Egypt", "Greece", "Rome", "Turkey"], a: 0 },
    { q: "Land of Thunder Dragon?", o: ["Nepal", "Bhutan", "Tibet", "China"], a: 1 },
    { q: "Land of Midnight Sun?", o: ["Norway", "Sweden", "Finland", "Denmark"], a: 0 },
    { q: "Which country has Eiffel Tower?", o: ["Italy", "France", "Spain", "Germany"], a: 1 },
    { q: "Which country has Great Wall?", o: ["India", "China", "Japan", "Korea"], a: 1 },
    { q: "Which country has Taj Mahal?", o: ["Pakistan", "India", "Bangladesh", "Nepal"], a: 1 },
    { q: "Which country has Statue of Liberty?", o: ["USA", "UK", "France", "Canada"], a: 0 },
    { q: "Which country has Colosseum?", o: ["Greece", "Italy", "Spain", "France"], a: 1 }
  ],
  science: [
    { q: "What is H2O?", o: ["Oxygen", "Hydrogen", "Water", "Salt"], a: 2 },
    { q: "What gas do plants absorb?", o: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"], a: 2 },
    { q: "Red planet?", o: ["Earth", "Mars", "Venus", "Jupiter"], a: 1 },
    { q: "Boiling point of water?", o: ["50°C", "100°C", "150°C", "200°C"], a: 1 },
    { q: "Center of atom?", o: ["Proton", "Electron", "Nucleus", "Neutron"], a: 2 },
    { q: "Breathing organ?", o: ["Heart", "Lungs", "Brain", "Liver"], a: 1 },
    { q: "Force pulling objects to Earth?", o: ["Magnetism", "Gravity", "Friction", "Energy"], a: 1 },
    { q: "Nearest star?", o: ["Moon", "Mars", "Sun", "Venus"], a: 2 },
    { q: "Symbol of Oxygen?", o: ["O", "Ox", "Og", "On"], a: 0 },
    { q: "Food making part of plant?", o: ["Root", "Stem", "Leaf", "Flower"], a: 2 },
    { q: "Largest organ?", o: ["Brain", "Liver", "Skin", "Heart"], a: 2 },
    { q: "Humans breathe in?", o: ["CO2", "O2", "N2", "H2"], a: 1 },
    { q: "Freezing point of water?", o: ["0°C", "10°C", "-10°C", "5°C"], a: 0 },
    { q: "Unit of force?", o: ["Joule", "Newton", "Watt", "Volt"], a: 1 },
    { q: "Closest planet to Sun?", o: ["Venus", "Earth", "Mercury", "Mars"], a: 2 },
    { q: "Brain function?", o: ["Pump blood", "Control body", "Digest food", "Breathe"], a: 1 },
    { q: "Energy is?", o: ["Matter", "Power to do work", "Heat", "Light"], a: 1 },
    { q: "Cells fighting infection?", o: ["RBC", "WBC", "Platelets", "Plasma"], a: 1 },
    { q: "Speed of light?", o: ["3×10^8 m/s", "100 m/s", "1000 m/s", "10 m/s"], a: 0 },
    { q: "DNA is?", o: ["Protein", "Genetic material", "Fat", "Vitamin"], a: 1 },
    { q: "Blood purifier?", o: ["Heart", "Liver", "Kidney", "Brain"], a: 2 },
    { q: "Smallest unit of life?", o: ["Atom", "Cell", "Tissue", "Organ"], a: 1 },
    { q: "Gas used in photosynthesis?", o: ["O2", "CO2", "H2", "N2"], a: 1 },
    { q: "SI unit of time?", o: ["Minute", "Hour", "Second", "Day"], a: 2 },
    { q: "Evaporation is?", o: ["Solid→Gas", "Liquid→Gas", "Gas→Liquid", "Solid→Liquid"], a: 1 },
    { q: "Sound is?", o: ["Light", "Energy wave", "Matter", "Gas"], a: 1 },
    { q: "Electricity is?", o: ["Heat", "Flow of electrons", "Light", "Force"], a: 1 },
    { q: "Friction is?", o: ["Push", "Pull", "Resistance force", "Motion"], a: 2 },
    { q: "Hardest substance?", o: ["Gold", "Iron", "Diamond", "Silver"], a: 2 },
    { q: "Magnet does?", o: ["Light", "Attract metal", "Heat", "Energy"], a: 1 },
    { q: "Unit of energy?", o: ["Watt", "Joule", "Volt", "Ampere"], a: 1 },
    { q: "Planet with rings?", o: ["Mars", "Earth", "Saturn", "Venus"], a: 2 },
    { q: "Gravity is?", o: ["Push", "Pull force", "Heat", "Energy"], a: 1 },
    { q: "Main gas in air?", o: ["Oxygen", "Nitrogen", "CO2", "Hydrogen"], a: 1 },
    { q: "Thermometer measures?", o: ["Weight", "Temperature", "Speed", "Light"], a: 1 },
    { q: "Solar energy comes from?", o: ["Wind", "Water", "Sun", "Heat"], a: 2 },
    { q: "Battery does?", o: ["Store energy", "Heat device", "Light device", "Sound device"], a: 0 },
    { q: "Acid taste?", o: ["Sweet", "Sour", "Bitter", "Salty"], a: 1 },
    { q: "Base taste?", o: ["Sour", "Bitter", "Sweet", "Neutral"], a: 1 },
    { q: "Neutral substance?", o: ["Acid", "Base", "Neither", "Salt"], a: 2 },
    { q: "Rusting is?", o: ["Burning", "Iron + Oxygen", "Melting", "Freezing"], a: 1 },
    { q: "Inertia is?", o: ["Force", "Resistance to change", "Energy", "Speed"], a: 1 },
    { q: "Motion is?", o: ["Rest", "Movement", "Energy", "Force"], a: 1 },
    { q: "Mass is?", o: ["Weight", "Amount of matter", "Speed", "Energy"], a: 1 },
    { q: "Light is?", o: ["Energy", "Matter", "Gas", "Liquid"], a: 0 },
    { q: "Heat is?", o: ["Energy", "Matter", "Light", "Gas"], a: 0 },
    { q: "Pressure is?", o: ["Force/Area", "Speed", "Energy", "Heat"], a: 0 },
    { q: "Unit of current?", o: ["Volt", "Ampere", "Watt", "Joule"], a: 1 },
    { q: "What is the SI unit of temperature?", o: ["Celsius", "Kelvin", "Fahrenheit", "Joule"], a: 1 },
    { q: "Which part of eye controls light?", o: ["Retina", "Cornea", "Iris", "Lens"], a: 2 }
  ],
  computer: [
    { q: "Which shortcut is used to copy selected text?", o: ["Ctrl + X", "Ctrl + C", "Ctrl + V", "Ctrl + Z"], a: 1 },
    { q: "Which shortcut is used to paste copied text?", o: ["Ctrl + V", "Ctrl + P", "Ctrl + X", "Ctrl + C"], a: 0 },
    { q: "Which shortcut is used to cut selected text?", o: ["Ctrl + X", "Ctrl + C", "Ctrl + V", "Ctrl + Z"], a: 0 },
    { q: "Which shortcut is used to undo an action?", o: ["Ctrl + Y", "Ctrl + Z", "Ctrl + X", "Ctrl + C"], a: 1 },
    { q: "Which shortcut is used to redo an action?", o: ["Ctrl + Z", "Ctrl + Y", "Ctrl + X", "Ctrl + C"], a: 1 },
    { q: "Which shortcut opens a new tab in browser?", o: ["Ctrl + T", "Ctrl + N", "Ctrl + W", "Ctrl + Tab"], a: 0 },
    { q: "Which shortcut closes the current tab?", o: ["Ctrl + W", "Ctrl + T", "Ctrl + N", "Ctrl + Q"], a: 0 },
    { q: "Which shortcut opens File Explorer?", o: ["Windows + E", "Ctrl + E", "Alt + E", "Windows + F"], a: 0 },
    { q: "Which shortcut locks the computer?", o: ["Windows + L", "Ctrl + L", "Alt + L", "Windows + K"], a: 0 },
    { q: "Which shortcut opens Task Manager?", o: ["Ctrl + Shift + Esc", "Ctrl + Alt + Del", "Alt + Tab", "Windows + M"], a: 0 },
    { q: "Which shortcut selects all text?", o: ["Ctrl + A", "Ctrl + S", "Ctrl + C", "Ctrl + X"], a: 0 },
    { q: "Which shortcut saves a document?", o: ["Ctrl + S", "Ctrl + P", "Ctrl + N", "Ctrl + O"], a: 0 },
    { q: "Which shortcut opens a document?", o: ["Ctrl + O", "Ctrl + N", "Ctrl + P", "Ctrl + S"], a: 0 },
    { q: "Which shortcut prints a document?", o: ["Ctrl + P", "Ctrl + S", "Ctrl + O", "Ctrl + N"], a: 0 },
    { q: "Which shortcut opens a new window?", o: ["Ctrl + N", "Ctrl + T", "Ctrl + W", "Alt + N"], a: 0 },
    { q: "Which shortcut switches between open windows?", o: ["Alt + Tab", "Ctrl + Tab", "Ctrl + Shift", "Windows + Tab"], a: 0 },
    { q: "Which shortcut minimizes all windows?", o: ["Windows + D", "Windows + M", "Alt + M", "Ctrl + M"], a: 0 },
    { q: "Which shortcut restores minimized windows?", o: ["Windows + D", "Windows + R", "Alt + D", "Ctrl + D"], a: 0 },
    { q: "Which shortcut finds text in a document?", o: ["Ctrl + F", "Ctrl + H", "Ctrl + G", "Ctrl + I"], a: 0 },
    { q: "Which shortcut replaces text in a document?", o: ["Ctrl + H", "Ctrl + F", "Ctrl + R", "Ctrl + G"], a: 0 },
    { q: "What does CPU stand for?", o: ["Central Process Unit", "Central Processing Unit", "Computer Personal Unit", "Central Peripheral Unit"], a: 1 },
    { q: "Which language is used for web apps?", o: ["Python", "JavaScript", "C++", "Java"], a: 1 },
    { q: "What does RAM stand for?", o: ["Random Access Memory", "Read Access Memory", "Run Access Memory", "Random Allocate Memory"], a: 0 },
    { q: "Which is not a programming language?", o: ["Python", "HTML", "Java", "C++"], a: 1 },
    { q: "Which is the primary language for Android development?", o: ["Java", "Swift", "C#", "Kotlin"], a: 3 },
    { q: "Which of these is an operating system?", o: ["Windows", "Python", "Chrome", "HTML"], a: 0 },
    { q: "What does HTML stand for?", o: ["HyperText Markup Language", "HyperText Makeup Language", "HighText Markup Language", "Hyper Tool Markup Language"], a: 0 },
    { q: "Which of these is used for database management?", o: ["MySQL", "Python", "C++", "HTML"], a: 0 },
    { q: "Which is the smallest unit of data in a computer?", o: ["Byte", "Bit", "Nibble", "Word"], a: 1 },
    { q: "What does URL stand for?", o: ["Uniform Resource Locator", "Universal Resource Link", "Uniform Reference Link", "Unified Resource Locator"], a: 0 },
    { q: "Which is a type of software?", o: ["System Software", "Application Software", "Both", "None"], a: 2 },
    { q: "Which is used to style web pages?", o: ["HTML", "CSS", "JavaScript", "Python"], a: 1 },
    { q: "Which of these is not a database?", o: ["Oracle", "MySQL", "MongoDB", "Photoshop"], a: 3 },
    { q: "Which is an example of a compiled language?", o: ["C", "Python", "PHP", "JavaScript"], a: 0 },
    { q: "Which is used for version control?", o: ["Git", "Python", "HTML", "CSS"], a: 0 },
    { q: "Which protocol is used to send emails?", o: ["FTP", "SMTP", "HTTP", "POP3"], a: 1 },
    { q: "Which one is a backend language?", o: ["PHP", "HTML", "CSS", "JavaScript"], a: 0 },
    { q: "Which is a frontend framework?", o: ["React", "Django", "Flask", "Laravel"], a: 0 },
    { q: "Which is a cloud service provider?", o: ["AWS", "Linux", "Python", "Git"], a: 0 },
    { q: "Which is the brain of the computer?", o: ["CPU", "RAM", "ROM", "GPU"], a: 0 },
    { q: "Which is used to make web pages interactive?", o: ["HTML", "CSS", "JavaScript", "SQL"], a: 2 },
    { q: "Which database is NoSQL?", o: ["MongoDB", "MySQL", "Oracle", "SQLite"], a: 0 },
    { q: "Which is a markup language?", o: ["HTML", "Python", "Java", "C#"], a: 0 },
    { q: "Which device is used for input?", o: ["Keyboard", "Monitor", "Printer", "Speaker"], a: 0 },
    { q: "Which device is used for output?", o: ["Keyboard", "Printer", "Mouse", "Scanner"], a: 1 },
    { q: "Which is a search engine?", o: ["Google", "Linux", "Windows", "Python"], a: 0 },
    { q: "Which one is an IDE?", o: ["Visual Studio", "Windows", "Python", "HTML"], a: 0 },
    { q: "Which is used to store large amounts of data?", o: ["Hard Disk", "RAM", "CPU", "Monitor"], a: 0 },
    { q: "Which is a computer network?", o: ["LAN", "ROM", "CPU", "Java"], a: 0 },
    { q: "Which is a protocol for secure communication?", o: ["HTTPS", "HTTP", "FTP", "SMTP"], a: 0 }
  ],
  pharmacy: [
    { q: "Which vitamin is essential for blood clotting?", o: ["Vitamin A", "Vitamin K", "Vitamin C", "Vitamin D"], a: 1 },
    { q: "Which drug is used as an analgesic?", o: ["Aspirin", "Amoxicillin", "Lisinopril", "Metformin"], a: 0 },
    { q: "Which organ metabolizes most drugs?", o: ["Kidney", "Liver", "Heart", "Lungs"], a: 1 },
    { q: "What is the main route for drug excretion?", o: ["Liver", "Kidney", "Lungs", "Skin"], a: 1 },
    { q: "Which antibiotic is penicillin-based?", o: ["Amoxicillin", "Ciprofloxacin", "Tetracycline", "Azithromycin"], a: 0 },
    { q: "Which drug reduces high blood pressure?", o: ["Metformin", "Amlodipine", "Paracetamol", "Omeprazole"], a: 1 },
    { q: "Which drug is used to treat diabetes?", o: ["Insulin", "Aspirin", "Omeprazole", "Loratadine"], a: 0 },
    { q: "Which type of drug relieves allergic reactions?", o: ["Antihistamine", "Antibiotic", "Analgesic", "Antipyretic"], a: 0 },
    { q: "Which drug reduces fever?", o: ["Paracetamol", "Amoxicillin", "Lisinopril", "Metformin"], a: 0 },
    { q: "Which drug is an anti-inflammatory?", o: ["Ibuprofen", "Insulin", "Omeprazole", "Amlodipine"], a: 0 },
    { q: "Which medication is used for asthma?", o: ["Albuterol", "Paracetamol", "Metformin", "Aspirin"], a: 0 },
    { q: "Which class of drugs reduces cholesterol?", o: ["Statins", "Beta-blockers", "Antibiotics", "NSAIDs"], a: 0 },
    { q: "Which drug treats bacterial infections?", o: ["Antibiotics", "Antivirals", "Antifungals", "Analgesics"], a: 0 },
    { q: "Which drug is antiviral?", o: ["Acyclovir", "Penicillin", "Paracetamol", "Ibuprofen"], a: 0 },
    { q: "Which drug treats fungal infections?", o: ["Fluconazole", "Amoxicillin", "Ibuprofen", "Paracetamol"], a: 0 },
    { q: "Which medication is used to prevent blood clots?", o: ["Warfarin", "Aspirin", "Amoxicillin", "Metformin"], a: 0 },
    { q: "Which vitamin deficiency causes scurvy?", o: ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin K"], a: 1 },
    { q: "Which vitamin is essential for bone health?", o: ["Vitamin C", "Vitamin D", "Vitamin K", "Vitamin B12"], a: 1 },
    { q: "Which electrolyte is important for heart function?", o: ["Potassium", "Calcium", "Sodium", "Magnesium"], a: 0 },
    { q: "Which drug is a proton pump inhibitor?", o: ["Omeprazole", "Metformin", "Paracetamol", "Aspirin"], a: 0 },
    { q: "Which drug reduces nausea?", o: ["Ondansetron", "Ibuprofen", "Amoxicillin", "Insulin"], a: 0 },
    { q: "Which drug treats depression?", o: ["Fluoxetine", "Paracetamol", "Amoxicillin", "Metformin"], a: 0 },
    { q: "Which drug is used for anxiety?", o: ["Diazepam", "Aspirin", "Amoxicillin", "Omeprazole"], a: 0 },
    { q: "Which drug is used to reduce inflammation in arthritis?", o: ["NSAIDs", "Insulin", "Metformin", "Amoxicillin"], a: 0 },
    { q: "Which drug treats hypertension?", o: ["Lisinopril", "Amoxicillin", "Paracetamol", "Aspirin"], a: 0 },
    { q: "Which drug treats heart failure?", o: ["Digoxin", "Amoxicillin", "Paracetamol", "Omeprazole"], a: 0 },
    { q: "Which type of insulin acts rapidly?", o: ["Rapid-acting", "Long-acting", "Intermediate", "Ultra-long"], a: 0 },
    { q: "Which drug prevents seizures?", o: ["Phenytoin", "Paracetamol", "Ibuprofen", "Amoxicillin"], a: 0 },
    { q: "Which drug treats epilepsy?", o: ["Valproate", "Ibuprofen", "Paracetamol", "Aspirin"], a: 0 },
    { q: "Which drug is used in tuberculosis?", o: ["Isoniazid", "Amoxicillin", "Paracetamol", "Ibuprofen"], a: 0 },
    { q: "Which vitamin deficiency causes rickets?", o: ["Vitamin A", "Vitamin D", "Vitamin C", "Vitamin K"], a: 1 },
    { q: "Which drug is used to reduce cholesterol absorption?", o: ["Ezetimibe", "Amoxicillin", "Ibuprofen", "Paracetamol"], a: 0 },
    { q: "Which drug treats migraine?", o: ["Sumatriptan", "Paracetamol", "Ibuprofen", "Amoxicillin"], a: 0 },
    { q: "Which drug is a beta-blocker?", o: ["Atenolol", "Paracetamol", "Amoxicillin", "Omeprazole"], a: 0 },
    { q: "Which drug treats gout?", o: ["Allopurinol", "Ibuprofen", "Paracetamol", "Amoxicillin"], a: 0 },
    { q: "Which drug treats anemia?", o: ["Iron Supplements", "Amoxicillin", "Ibuprofen", "Paracetamol"], a: 0 },
    { q: "Which vitamin is essential for nerve function?", o: ["Vitamin B12", "Vitamin C", "Vitamin D", "Vitamin K"], a: 0 },
    { q: "Which drug treats fungal skin infections?", o: ["Clotrimazole", "Amoxicillin", "Paracetamol", "Ibuprofen"], a: 0 },
    { q: "Which drug is a corticosteroid?", o: ["Prednisone", "Ibuprofen", "Paracetamol", "Amoxicillin"], a: 0 },
    { q: "Which drug treats high uric acid levels?", o: ["Allopurinol", "Paracetamol", "Ibuprofen", "Amoxicillin"], a: 0 },
    { q: "Which drug treats Parkinson’s disease?", o: ["Levodopa", "Amoxicillin", "Paracetamol", "Ibuprofen"], a: 0 },
    { q: "Which drug treats Alzheimer’s disease?", o: ["Donepezil", "Paracetamol", "Ibuprofen", "Amoxicillin"], a: 0 },
    { q: "Which drug is used to treat inflammation in allergies?", o: ["Corticosteroid", "Amoxicillin", "Ibuprofen", "Paracetamol"], a: 0 },
    { q: "Which drug is used to treat cold and cough?", o: ["Dextromethorphan", "Amoxicillin", "Paracetamol", "Ibuprofen"], a: 0 },
    { q: "Which drug is a bronchodilator?", o: ["Salbutamol", "Paracetamol", "Amoxicillin", "Ibuprofen"], a: 0 },
    { q: "Which drug treats constipation?", o: ["Laxatives", "Amoxicillin", "Paracetamol", "Ibuprofen"], a: 0 },
    { q: "Which drug treats diarrhea?", o: ["Loperamide", "Paracetamol", "Ibuprofen", "Amoxicillin"], a: 0 },
    { q: "Which drug treats fungal infections in mouth?", o: ["Nystatin", "Amoxicillin", "Paracetamol", "Ibuprofen"], a: 0 },
    { q: "Which drug prevents osteoporosis?", o: ["Calcium and Vitamin D", "Ibuprofen", "Amoxicillin", "Paracetamol"], a: 0 },
    { q: "Which drug is used to treat hyperthyroidism?", o: ["Methimazole", "Amoxicillin", "Paracetamol", "Ibuprofen"], a: 0 }
  ],
  mixed: [
    { q: "Who is known as the Father of Computers?", o: ["Charles Babbage", "Alan Turing", "Bill Gates", "Steve Jobs"], a: 0 },
    { q: "Which organ purifies blood in the human body?", o: ["Heart", "Kidney", "Liver", "Lungs"], a: 1 },
    { q: "Which protocol is used to transfer web pages?", o: ["FTP", "SMTP", "HTTP", "SSH"], a: 2 },
    { q: "What is the normal human body temperature?", o: ["37°C", "40°C", "35°C", "32°C"], a: 0 },
    { q: "Which medicine is commonly used to reduce fever?", o: ["Paracetamol", "Cetrizine", "Azithromycin", "Insulin"], a: 0 },
    { q: "Which data structure works on FIFO principle?", o: ["Stack", "Queue", "Tree", "Graph"], a: 1 },
    { q: "Which blood group is known as universal donor?", o: ["A+", "O-", "AB+", "B+"], a: 1 },
    { q: "Which language is mainly used for web page styling?", o: ["Python", "CSS", "Java", "C++"], a: 1 },
    { q: "What is the powerhouse of the cell?", o: ["Nucleus", "Ribosome", "Mitochondria", "Golgi body"], a: 2 },
    { q: "Which company developed JavaScript?", o: ["Microsoft", "Netscape", "Google", "IBM"], a: 1 },
    { q: "Which gas is essential for human respiration?", o: ["Nitrogen", "Hydrogen", "Oxygen", "Carbon dioxide"], a: 2 },
    { q: "Which branch of pharmacy deals with drug preparation?", o: ["Pharmacology", "Pharmaceutics", "Toxicology", "Biochemistry"], a: 1 },
    { q: "Which planet is known as the Red Planet?", o: ["Earth", "Venus", "Mars", "Jupiter"], a: 2 },
    { q: "Which HTML tag is used to create a hyperlink?", o: ["<img>", "<a>", "<p>", "<h1>"], a: 1 },
    { q: "What is the SI unit of force?", o: ["Joule", "Newton", "Pascal", "Watt"], a: 1 },
    { q: "Which medicine is an antibiotic?", o: ["Amoxicillin", "Paracetamol", "Metformin", "Aspirin"], a: 0 },
    { q: "Which part of computer stores permanent data?", o: ["RAM", "ROM", "Cache", "Register"], a: 1 },
    { q: "What is the largest organ in the human body?", o: ["Heart", "Skin", "Liver", "Lungs"], a: 1 },
    { q: "Which keyword is used to declare a variable in JavaScript?", o: ["int", "var", "string", "float"], a: 1 },
    { q: "Which disease is caused by insulin deficiency?", o: ["Hypertension", "Diabetes", "Asthma", "Cancer"], a: 1 },
    { q: "Which country is known as the Land of Rising Sun?", o: ["China", "Japan", "India", "Thailand"], a: 1 },
    { q: "What is the brain of the computer?", o: ["RAM", "CPU", "Hard Disk", "GPU"], a: 1 },
    { q: "Which vitamin helps in blood clotting?", o: ["Vitamin A", "Vitamin K", "Vitamin C", "Vitamin D"], a: 1 },
    { q: "Which operator is used for strict equality in JavaScript?", o: ["=", "==", "===", "!="], a: 2 },
    { q: "What is the chemical symbol for Sodium?", o: ["So", "Na", "S", "Sd"], a: 1 },
    { q: "Which dosage form is injected directly into veins?", o: ["Tablet", "Capsule", "Intravenous injection", "Syrup"], a: 2 },
    { q: "What does URL stand for?", o: ["Uniform Resource Locator", "Universal Resource Link", "Unique Resource Locator", "Uniform Read Locator"], a: 0 },
    { q: "Which organ controls the nervous system?", o: ["Heart", "Brain", "Kidney", "Liver"], a: 1 },
    { q: "Which scientist discovered gravity?", o: ["Newton", "Einstein", "Tesla", "Darwin"], a: 0 },
    { q: "Which JavaScript method converts JSON into object?", o: ["JSON.parse()", "JSON.stringify()", "parseJSON()", "toObject()"], a: 0 },
    { q: "Which blood cells fight infections?", o: ["RBC", "WBC", "Platelets", "Plasma"], a: 1 },
    { q: "What is the full form of USB?", o: ["Universal Serial Bus", "United System Bus", "Universal System Backup", "Ultra Serial Bus"], a: 0 },
    { q: "Which medicine is commonly used for allergies?", o: ["Cetirizine", "Metformin", "Aspirin", "Omeprazole"], a: 0 },
    { q: "What is the capital of India?", o: ["Mumbai", "Delhi", "Kolkata", "Chennai"], a: 1 },
    { q: "Which loop runs at least once in JavaScript?", o: ["for", "while", "do...while", "foreach"], a: 2 },
    { q: "Which part of plant performs photosynthesis?", o: ["Root", "Stem", "Leaf", "Flower"], a: 2 },
    { q: "Which protocol is used for secure websites?", o: ["HTTP", "HTTPS", "FTP", "SMTP"], a: 1 },
    { q: "Which vitamin deficiency causes scurvy?", o: ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"], a: 2 },
    { q: "Which is the fastest memory in computer?", o: ["RAM", "ROM", "Cache", "Hard Disk"], a: 2 },
    { q: "What is the national animal of India?", o: ["Lion", "Elephant", "Tiger", "Peacock"], a: 2 },
    { q: "Which medicine reduces stomach acidity?", o: ["Omeprazole", "Paracetamol", "Azithromycin", "Cetirizine"], a: 0 },
    { q: "Which company developed Windows OS?", o: ["Apple", "IBM", "Microsoft", "Google"], a: 2 },
    { q: "What is the study of living organisms called?", o: ["Physics", "Chemistry", "Biology", "Geology"], a: 2 },
    { q: "Which keyword is used for function in JavaScript?", o: ["func", "method", "function", "define"], a: 2 },
    { q: "Which blood vessels carry blood to the heart?", o: ["Arteries", "Veins", "Capillaries", "Aorta"], a: 1 },
    { q: "What is H2O commonly known as?", o: ["Hydrogen", "Oxygen", "Salt", "Water"], a: 3 },
    { q: "Which medicine is used for diabetes?", o: ["Insulin", "Ibuprofen", "Amoxicillin", "Cetirizine"], a: 0 },
    { q: "Which device is used to input text into a computer?", o: ["Monitor", "Keyboard", "Speaker", "Printer"], a: 1 },
    { q: "Which gas do plants absorb from atmosphere?", o: ["Oxygen", "Carbon dioxide", "Hydrogen", "Nitrogen"], a: 1 },
    { q: "Which continent is the largest?", o: ["Africa", "Asia", "Europe", "Australia"], a: 1 }
  ]
};
